#!/usr/bin/env python
"""
Track 2: Fine-Tuning Pipeline for StreamingVLM on AMD MI300X

Prepares and runs SFT on Qwen2.5-VL with sports commentary data.
Uses StreamingVLM's training pipeline adapted for football commentary.

Two stages:
- Stage 1: Main SFT on sports commentary data
- Stage 2: High-quality annealing on curated football commentary

Usage:
  python scripts/prepare_sft_data.py --output ./sft_data
  python scripts/run_sft_amd.py --stage 1 --data ./sft_data
"""
import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

# ── Paths ─────────────────────────────────────────────────────────────────────

STREAMING_VLM_PATH = "/home/deepu/PitchSideAI/streaming-vlm-qwen3-rocm"
PITCHSIDEAI_PATH = "/home/deepu/PitchSideAI"
SFT_SCRIPT_TEMPLATE = """#!/bin/bash
# SFT Training Script for StreamingVLM on AMD MI300X
# Generated by PitchSideAI's Track 2 pipeline
set -e

export ROCM_PATH=/opt/rocm
export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export PYTORCH_ROCM_ARCH=gfx942

# Model and data paths
export MODEL_PATH="{model_path}"
export DATASET_PATH="{dataset_path}"
export OUTPUT_DIR="{output_dir}"

# Training hyperparameters
export WINDOW_SIZE={window_size}
export CHUNK_DURATION={chunk_duration}
export NUM_EPOCHS={num_epochs}
export LEARNING_RATE={learning_rate}
export BATCH_SIZE={batch_size}
export GRADIENT_ACCUMULATION={gradient_accumulation}

cd {streaming_vlm_path}
conda activate streamingvlm-sft

# Stage {stage}: {stage_description}
echo "Starting Stage {stage} SFT..."
echo "Model: $MODEL_PATH"
echo "Data: $DATASET_PATH"
echo "Output: $OUTPUT_DIR"

torchrun --nproc_per_node=8 train.py \
    --pretrained_model_name_or_path "$MODEL_PATH" \
    --dataset_path "$DATASET_PATH" \
    --output_dir "$OUTPUT_DIR" \
    --window_size "$WINDOW_SIZE" \
    --chunk_duration "$CHUNK_DURATION" \
    --num_train_epochs "$NUM_EPOCHS" \
    --per_device_train_batch_size "$BATCH_SIZE" \
    --gradient_accumulation_steps "$GRADIENT_ACCUMULATION" \
    --learning_rate "$LEARNING_RATE" \
    --warmup_ratio 0.03 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 500 \
    --bf16 true \
    --tf32 false \
    --gradient_checkpointing true \
    --dataloader_num_workers 4 \
    --report_to wandb \
    --run_name "{run_name}"

echo "Stage {stage} SFT complete!"
"""


# ── Dataset Preparation ────────────────────────────────────────────────────────

@dataclass
class CommentarySample:
    """A single commentary sample for SFT."""
    video_path: str
    start_time: float
    end_time: float
    commentary: str
    tactical_label: str
    confidence: float = 1.0


def create_sport_commentary_samples(
    sport: str = "football",
    include_synthetic: bool = True,
) -> List[CommentarySample]:
    """
    Create or load sports commentary samples for SFT.

    For the hackathon, we use:
    1. LiveSports3k-cc: StreamingVLM's sports benchmark
    2. Synthetic football commentary (generated from stats)
    3. User-provided match videos + commentary
    """
    samples = []

    # Use LiveSports3k-cc if available
    livesports_path = os.environ.get("LIVESPORTS3K_PATH", "")
    if livesports_path and os.path.isdir(livesports_path):
        samples.extend(_load_livesports_samples(livesports_path))

    # Generate synthetic commentary from football data
    if include_synthetic and len(samples) < 1000:
        synthetic = _generate_synthetic_commentary(
            num_samples=2000 - len(samples),
            sport=sport,
        )
        samples.extend(synthetic)

    return samples


def _load_livesports_samples(data_path: str) -> List[CommentarySample]:
    """Load commentary samples from LiveSports3k-cc dataset."""
    samples = []
    video_dir = os.path.join(data_path, "videos")
    if not os.path.isdir(video_dir):
        return samples

    for video_file in sorted(os.listdir(video_dir))[:100]:
        if not video_file.endswith((".mp4", ".mkv", ".webm")):
            continue
        video_path = os.path.join(video_dir, video_file)
        # Create commentary sample from filename structure
        # LiveSports3k format: sport_match_timestamp.mp4
        name = os.path.splitext(video_file)[0]
        samples.append(CommentarySample(
            video_path=video_path,
            start_time=0.0,
            end_time=60.0,
            commentary=name.replace("_", " ").title(),
            tactical_label="Live Match",
            confidence=0.8,
        ))
    return samples


def _generate_synthetic_commentary(
    num_samples: int = 1000,
    sport: str = "football",
) -> List[CommentarySample]:
    """
    Generate synthetic commentary data using football templates.

    For a real submission, you'd use actual match footage + commentary.
    This provides a scaffold that you can replace with real data.
    """
    templates = [
        "A brilliant passage of play from {team}! The movement off the ball is exceptional.",
        "{team} building from the back, patiently waiting for the right moment to strike.",
        "That's a tactical foul from {team}, stopping a dangerous counter-attack.",
        "The press from {team} is relentless! They're forcing errors high up the pitch.",
        "{player} with a moment of individual brilliance! That's world-class.",
        "Set piece opportunity for {team}. The delivery has to be perfect here.",
        "Counter-attack! {team} breaking at pace, {player_count} vs {defender_count}!",
        "The goalkeeper comes out to claim — and does so with authority.",
        "That's a corner kick for {team}. The big men are coming forward.",
        "Substitution being prepared on the sidelines. Fresh legs coming on for {team}.",
        "The referee has a word with {player}. Needs to be careful now.",
        "What a save! The goalkeeper at full stretch to deny {team}!",
        "Penalty appeal! The {team} players are surrounding the referee!",
        "The tempo has dropped here in the last few minutes. {team} happy to keep possession.",
        "Overlapping run down the flank! The fullback joins the attack for {team}.",
    ]

    tactical_labels = [
        "Build Up", "Counter Attack", "Set Piece", "Defensive Stand",
        "Goal Attempt", "Ball Recovery", "Midfield Battle", "Wings Play",
        "Pressing", "Open Play", "Goalkeeper Save", "Substitution",
        "Tactical Foul", "Possession Play", "Overlapping Run",
    ]

    teams = ["Manchester City", "Liverpool", "Arsenal", "Barcelona",
             "Real Madrid", "Bayern Munich", "Paris Saint-Germain",
             "Manchester United", "Chelsea", "Inter Milan"]
    players = ["Mbappe", "Haaland", "Salah", "De Bruyne", "Vinicius",
               "Bellingham", "Kane", "Rodri", "Saka", "Foden"]

    samples = []
    import random
    rng = random.Random(42)

    for i in range(num_samples):
        template = rng.choice(templates)
        team = rng.choice(teams)
        commentary = template.format(
            team=team,
            player=rng.choice(players),
            player_count=rng.choice(["2", "3", "4"]),
            defender_count=rng.choice(["2", "3"]),
        )
        samples.append(CommentarySample(
            video_path="synthetic",
            start_time=i * 5.0,
            end_time=(i + 1) * 5.0,
            commentary=commentary,
            tactical_label=rng.choice(tactical_labels),
            confidence=0.85,
        ))

    return samples


def convert_to_streaming_vlm_format(
    samples: List[CommentarySample],
    output_path: str,
    system_prompt: str = "",
) -> str:
    """
    Convert commentary samples to StreamingVLM's dataset format.

    StreamingVLM expects JSONL with:
    {
        "conversation": [
            {"role": "previous text", "content": "..."},
            {"role": "user", "content": [{"type": "text", "text": "Time=X-Ys"}, {"type": "video", "video": "..."}, {"type": "text", "text": "Commentate this match"}]},
            {"role": "assistant", "content": "..."}
        ],
        "start_timestamp": 0.0,
        "end_timestamp": 60.0
    }
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    with open(output_path, "w") as f:
        for sample in samples:
            record = {
                "conversation": [
                    {"role": "previous text",
                     "content": system_prompt or f"This is a {sample.tactical_label} moment in a football match."},
                    {"role": "user", "content": [
                        {"type": "text",
                         "text": f"Time={sample.start_time:.1f}-{sample.end_time:.1f}s"},
                        {"type": "video", "video": sample.video_path},
                        {"type": "text", "text": "Commentate on this match"},
                    ]},
                    {"role": "assistant",
                     "content": sample.commentary},
                ],
                "start_timestamp": sample.start_time,
                "end_timestamp": sample.end_time,
                "tactical_label": sample.tactical_label,
                "confidence": sample.confidence,
            }
            f.write(json.dumps(record) + "\n")

    return output_path


# ── AMD MI300X SFT Runner ─────────────────────────────────────────────────────

def generate_sft_script(
    stage: int,
    model_path: str,
    dataset_path: str,
    output_dir: str,
    window_size: int = 16,
    chunk_duration: int = 1,
    num_epochs: int = 3,
    learning_rate: float = 2e-5,
    batch_size: int = 1,
    gradient_accumulation: int = 8,
) -> str:
    """Generate the SFT training script for AMD MI300X."""
    stage_desc = {
        1: "Main SFT on sports commentary data",
        2: "High-quality annealing on curated football data",
    }

    script = SFT_SCRIPT_TEMPLATE.format(
        model_path=model_path,
        dataset_path=dataset_path,
        output_dir=output_dir,
        window_size=window_size,
        chunk_duration=chunk_duration,
        num_epochs=num_epochs,
        learning_rate=learning_rate,
        batch_size=batch_size,
        gradient_accumulation=gradient_accumulation,
        streaming_vlm_path=STREAMING_VLM_PATH,
        stage=stage,
        stage_description=stage_desc.get(stage, "SFT Training"),
        run_name=f"pitchsideai-streaming-vlm-stage{stage}",
    )

    script_path = f"/home/deepu/PitchSideAI/scripts/sft_stage_{stage}_amd.sh"
    os.makedirs(os.path.dirname(script_path), exist_ok=True)
    with open(script_path, "w") as f:
        f.write(script)

    os.chmod(script_path, 0o755)
    return script_path


# ── CLI ────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="PitchSideAI Track 2: SFT Pipeline for AMD MI300X"
    )
    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # prepare-data
    prep = subparsers.add_parser("prepare-data", help="Prepare SFT dataset")
    prep.add_argument("--output", default="./sft_data", help="Output directory")
    prep.add_argument("--sport", default="football")
    prep.add_argument("--num-synthetic", type=int, default=2000)
    prep.add_argument("--livesports-path", default="")

    # generate-script
    gen = subparsers.add_parser("generate-script", help="Generate SFT training script")
    gen.add_argument("--stage", type=int, required=True, choices=[1, 2])
    gen.add_argument("--model", default="mit-han-lab/StreamingVLM")
    gen.add_argument("--dataset", required=True)
    gen.add_argument("--output-dir", required=True)
    gen.add_argument("--window-size", type=int, default=16)
    gen.add_argument("--epochs", type=int, default=3)
    gen.add_argument("--lr", type=float, default=2e-5)
    gen.add_argument("--batch-size", type=int, default=1)
    gen.add_argument("--grad-accum", type=int, default=8)

    # run-local-check
    check = subparsers.add_parser("check", help="Verify SFT env is ready (no GPU needed)")

    args = parser.parse_args()

    if args.command == "prepare-data":
        print(f"Preparing SFT data for {args.sport}...")
        if args.livesports_path:
            os.environ["LIVESPORTS3K_PATH"] = args.livesports_path

        samples = create_sport_commentary_samples(
            sport=args.sport,
            include_synthetic=True,
        )
        output_file = os.path.join(args.output, "commentary_sft.jsonl")
        os.makedirs(args.output, exist_ok=True)

        path = convert_to_streaming_vlm_format(samples, output_file)
        print(f"Created {len(samples)} samples at {path}")
        print(f"\nTactical label distribution:")
        labels = {}
        for s in samples:
            labels[s.tactical_label] = labels.get(s.tactical_label, 0) + 1
        for label, count in sorted(labels.items(), key=lambda x: -x[1]):
            print(f"  {label}: {count}")

    elif args.command == "generate-script":
        script_path = generate_sft_script(
            stage=args.stage,
            model_path=args.model,
            dataset_path=args.dataset,
            output_dir=args.output_dir,
            window_size=args.window_size,
            num_epochs=args.epochs,
            learning_rate=args.lr,
            batch_size=args.batch_size,
            gradient_accumulation=args.grad_accum,
        )
        print(f"Generated SFT script: {script_path}")
        print(f"\nRun on MI300X:")
        print(f"  bash {script_path}")

    elif args.command == "check":
        print("Checking SFT environment...")
        checks = {
            "StreamingVLM repo": os.path.isdir(STREAMING_VLM_PATH),
            "train.py exists": os.path.isfile(os.path.join(STREAMING_VLM_PATH, "train.py")),
            "StreamingVLM module": os.path.isdir(
                os.path.join(STREAMING_VLM_PATH, "streaming_vlm")),
        }
        all_ok = True
        for check_name, result in checks.items():
            status = "OK" if result else "MISSING"
            if not result:
                all_ok = False
            print(f"  [{status}] {check_name}")

        if all_ok:
            print("\nEnvironment ready for SFT on AMD MI300X!")
            print("Next steps:")
            print("  1. python scripts/prepare_sft_data.py prepare-data --output ./sft_data")
            print("  2. python scripts/prepare_sft_data.py generate-script --stage 1 --dataset ./sft_data --output-dir ./checkpoints_sft")
            print("  3. scp scripts/ and sft_data/ to MI300X instance")
            print("  4. bash scripts/sft_stage_1_amd.sh")
        else:
            print("\nFix missing items before proceeding.")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
