#!/bin/bash
# SFT Training Script for StreamingVLM on AMD MI300X
# Generated by PitchSideAI's Track 2 pipeline
set -e

export ROCM_PATH=/opt/rocm
export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export PYTORCH_ROCM_ARCH=gfx942

# Model and data paths
export MODEL_PATH="mit-han-lab/StreamingVLM"
export DATASET_PATH="./sft_data"
export OUTPUT_DIR="./checkpoints_sft_amd"

# Training hyperparameters
export WINDOW_SIZE=16
export CHUNK_DURATION=1
export NUM_EPOCHS=3
export LEARNING_RATE=2e-05
export BATCH_SIZE=1
export GRADIENT_ACCUMULATION=8

cd /home/deepu/streaming-vlm
conda activate streamingvlm-sft

# Stage 1: Main SFT on sports commentary data
echo "Starting Stage 1 SFT..."
echo "Model: $MODEL_PATH"
echo "Data: $DATASET_PATH"
echo "Output: $OUTPUT_DIR"

torchrun --nproc_per_node=8 train.py     --pretrained_model_name_or_path "$MODEL_PATH"     --dataset_path "$DATASET_PATH"     --output_dir "$OUTPUT_DIR"     --window_size "$WINDOW_SIZE"     --chunk_duration "$CHUNK_DURATION"     --num_train_epochs "$NUM_EPOCHS"     --per_device_train_batch_size "$BATCH_SIZE"     --gradient_accumulation_steps "$GRADIENT_ACCUMULATION"     --learning_rate "$LEARNING_RATE"     --warmup_ratio 0.03     --lr_scheduler_type cosine     --logging_steps 10     --save_steps 500     --bf16 true     --tf32 false     --gradient_checkpointing true     --dataloader_num_workers 4     --report_to wandb     --run_name "pitchsideai-streaming-vlm-stage1"

echo "Stage 1 SFT complete!"
